apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mistral-7b-ollama-pvc
    namespace: homelab-ai
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: local-path
    resources:
        requests:
            storage: 10Gi
