apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: qwen2-05b-models-pvc
    namespace: homelab-ai
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: local-path
    resources:
        requests:
            storage: 5Gi
