apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: qwen2-05b-ingress
    namespace: homelab-ai
spec:
    rules:
        - host: qwen2-05b.llm.lan
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: qwen2-05b
                            port:
                                number: 80
